name: Check C++ Blackjack Program

on: [push]

env:
  MIN_COVERAGE_REQUIRED: 75

jobs:
  cpp-test-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up C++ environment
      uses: actions/setup-cpp@v2
      with:
        compiler: 'gcc'  # Adjust based on your preferred C++ compiler

    - name: Install CMake
      run: sudo apt-get install -y cmake

    - name: Build C++ program
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run Unit Tests
      run: |
        cd build
        make test

    - name: Check Code Coverage
      run: |
        cd build
        ctest --verbose
        gcovr -r .. --exclude 'tests/*' --exclude 'CMakeFiles/*' --exclude 'external/*' -e 'vendor/*'

    - name: Calculate Code Coverage Percentage
      id: total-coverage
      run: |
        total_lines=$(gcovr -r .. --exclude 'tests/*' --exclude 'CMakeFiles/*' --exclude 'external/*' -e 'vendor/*' -a | grep -oP '\s+\d+\.\d+\% lines' | grep -oP '\d+\.\d+')
        is_covered=$(awk 'BEGIN { print ('$total_lines' >= '$MIN_COVERAGE_REQUIRED') }')
        echo "Coverage is: $total_lines%"
        exit $is_covered

        - name: Set Up ClangFormat
      run: sudo apt-get install -y clang-format

    - name: Run ClangFormat
      run: clang-format --version && clang-format -style=file -output-replacements-xml main.cpp Simulation.cpp | grep "<replacement " && exit 1 || exit 0
