name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install ClangFormat
      run: sudo apt-get install clang-format

    - name: Run ClangFormat
      run: clang-format --version && clang-format -i -style=file *.cpp
      
    - name: Set up CMake
      working-directory: ./googletest
      run: cmake -S /home/runner/work/blackjack/googletest -B build

    - name: Build with Make
      working-directory: ./googletest
      run: cmake --build build

    - name: Run unit tests
      run: ./build/test/unit_tests
